apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-app1
  name: devops-app1-service
spec:
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: devops-app1-pod
  type: ClusterIP